<a href="https://colab.research.google.com/github/patbpm/Hamoye_quiz/blob/master/Hamoye_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

**Importing the Data**

In [11]:
#Data of the the Appliances Energy Prediction
url = 'https://raw.githubusercontent.com/patbpm/Hamoye_quiz/master/hamayo_regression/energydata_complete.csv'

appliance_energy_data_df = pd.read_csv(url)

**DATA EDA**

In [12]:
appliance_energy_data_df.head()

                  date  Appliances  lights  ...  Tdewpoint        rv1        rv2
0  2016-01-11 17:00:00          60      30  ...        5.3  13.275433  13.275433
1  2016-01-11 17:10:00          60      30  ...        5.2  18.606195  18.606195
2  2016-01-11 17:20:00          50      30  ...        5.1  28.642668  28.642668
3  2016-01-11 17:30:00          50      40  ...        5.0  45.410389  45.410389
4  2016-01-11 17:40:00          60      40  ...        4.9  10.084097  10.084097

[5 rows x 29 columns]

In [13]:
appliance_energy_data_df.describe()

         Appliances        lights  ...           rv1           rv2
count  19735.000000  19735.000000  ...  19735.000000  19735.000000
mean      97.694958      3.801875  ...     24.988033     24.988033
std      102.524891      7.935988  ...     14.496634     14.496634
min       10.000000      0.000000  ...      0.005322      0.005322
25%       50.000000      0.000000  ...     12.497889     12.497889
50%       60.000000      0.000000  ...     24.897653     24.897653
75%      100.000000      0.000000  ...     37.583769     37.583769
max     1080.000000     70.000000  ...     49.996530     49.996530

[8 rows x 28 columns]

In [14]:
appliance_energy_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         19735 non-null  object
 1   Appliances   19735 non-null  int64
 2   lights       19735 non-null  int64
 3   T1           19735 non-null  float64
 4   RH_1         19735 non-null  float64
 5   T2           19735 non-null  float64
 6   RH_2         19735 non-null  float64
 7   T3           19735 non-null  float64
 8   RH_3         19735 non-null  float64
 9   T4           19735 non-null  float64
 10  RH_4         19735 non-null  float64
 11  T5           19735 non-null  float64
 12  RH_5         19735 non-null  float64
 13  T6           19735 non-null  float64
 14  RH_6         19735 non-null  float64
 15  T7           19735 non-null  float64
 16  RH_7         19735 non-null  float64
 17  T8           19735 non-null  float64
 18  RH_8         19735 non-null  float64
 19  T9           19735 non-null  float64
 20  RH_9         19735 non-null  float64
 21  T_out        19735 non-null  float64
 22  Press_mm_hg  19735 non-null  float64
 23  RH_out       19735 non-null  float64
 24  Windspeed    19735 non-null  float64
 25  Visibility   19735 non-null  float64
 26  Tdewpoint    19735 non-null  float64
 27  rv1          19735 non-null  float64
 28  rv2          19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [18]:
appliance_energy_data_df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [19]:
appliance_energy_data_df.shape

(19735, 29)

In [16]:
# Checking to see if there are any missing values 
appliance_energy_data_df.isnull().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [17]:
#just an overview of correlation between variables
appliance_energy_data_df.corr()

             Appliances    lights        T1  ...  Tdewpoint       rv1       rv2
Appliances     1.000000  0.197278  0.055447  ...   0.015353 -0.011145 -0.011145
lights         0.197278  1.000000 -0.023528  ...  -0.036322  0.000521  0.000521
T1             0.055447 -0.023528  1.000000  ...   0.571309 -0.006203 -0.006203
RH_1           0.086031  0.106968  0.164006  ...   0.639106 -0.000699 -0.000699
T2             0.120073 -0.005622  0.836834  ...   0.582602 -0.011087 -0.011087
RH_2          -0.060465  0.050985 -0.002509  ...   0.499152  0.006275  0.006275
T3             0.085060 -0.097393  0.892402  ...   0.645886 -0.005194 -0.005194
RH_3           0.036292  0.131161 -0.028550  ...   0.414387 -0.000477 -0.000477
T4             0.040281 -0.008859  0.877001  ...   0.519471 -0.001815 -0.001815
RH_4           0.016965  0.114936  0.097861  ...   0.616509 -0.001787 -0.001787
T5             0.019760 -0.078745  0.885247  ...   0.588362 -0.005490 -0.005490
RH_5           0.006955  0.141233 -0.014782  ...   0.078175 -0.011056 -0.011056
T6             0.117638 -0.079029  0.654769  ...   0.764242 -0.015086 -0.015086
RH_6          -0.083178  0.153756 -0.615045  ...  -0.260417  0.011671  0.011671
T7             0.025801 -0.135347  0.838705  ...   0.466625 -0.003900 -0.003900
RH_7          -0.055642  0.035069  0.135182  ...   0.641857  0.001820  0.001820
T8             0.039572 -0.071458  0.825413  ...   0.391810 -0.003210 -0.003210
RH_8          -0.094039  0.012915 -0.006441  ...   0.501775  0.004480  0.004480
T9             0.010010 -0.157592  0.844777  ...   0.581483 -0.001227 -0.001227
RH_9          -0.051462 -0.008766  0.071756  ...   0.540328 -0.002955 -0.002955
T_out          0.099155 -0.074424  0.682846  ...   0.790661 -0.015216 -0.015216
Press_mm_hg   -0.034885 -0.010576 -0.150574  ...  -0.244098  0.000699  0.000699
RH_out        -0.152282  0.068543 -0.345481  ...   0.036506  0.020441  0.020441
Windspeed      0.087122  0.060281 -0.087654  ...   0.125972 -0.011342 -0.011342
Visibility     0.000230  0.020038 -0.076210  ...  -0.042190 -0.005889 -0.005889
Tdewpoint      0.015353 -0.036322  0.571309  ...   1.000000 -0.003943 -0.003943
rv1           -0.011145  0.000521 -0.006203  ...  -0.003943  1.000000  1.000000
rv2           -0.011145  0.000521 -0.006203  ...  -0.003943  1.000000  1.000000

[28 rows x 28 columns]

In [20]:
# drop lights column and date column 
appliance_energy_data_df.drop(['lights'], axis=1,inplace=True)

appliance_energy_data_df.drop(['date'], axis=1, inplace=True)

# **REGRESSION PROCESS**

In [21]:
#Normalization of the Dataset using MinMaxScaler and split the data into independent(X variable) and dependent(Y variable) variables
from sklearn.preprocessing import MinMaxScaler
Scaler = MinMaxScaler()
normalised_data = pd.DataFrame(Scaler.fit_transform(appliance_energy_data_df), columns = appliance_energy_data_df.columns)
features= normalised_data.drop(columns= ['Appliances'])
target = normalised_data['Appliances']

In [24]:
print(features.shape)
print(target.shape)

(19735, 26)
(19735,)

In [25]:
# splitting data into training and testing set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size = 0.3, random_state = 42)

In [30]:
print(f'shape of training set is {x_train.shape}')
print(f'shape of testing set is {x_test.shape}')

shape of training set is (13814, 26)
shape of testing set is (5921, 26)

In [31]:
#fitting the model to the training dataset and deriving the predictions
linear_model = LinearRegression()
linear_model.fit(x_train, y_train)
predicted_values = linear_model.predict(x_test)

In [32]:
# Calculation of Mean absolute error to 2 decimal places
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, predicted_values)
round(mae, 2)

0.05

In [34]:
# Calaculation of R-squared or coefficient of determination to 2 decimal places
from sklearn.metrics import r2_score
r_square_score = r2_score(y_test, predicted_values)
round(r_square_score, 2)

0.15

In [35]:
# Calculate the Residual Sum of Squares to 2 decimal places
import numpy as np
rss = np.sum(np.square(y_test - predicted_values))
round(rss, 2)

45.35

In [36]:
# Calaculate the Root Mean Square Error to 3 decimal places
from sklearn.metrics import  mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, predicted_values))
round(rmse, 3)

0.088

In [37]:
# Calculate the finding R-Squared
from sklearn.metrics import r2_score
R_Squared = r2_score(y_test, predicted_values)
round(R_Squared, 3)

0.149

In [42]:
#Ridge Regresssion and finding the Root Mean Square Error
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train, y_train)

predicted_test = ridge_reg.predict(x_test)

rmse = np.sqrt(mean_squared_error(y_test, predicted_test))
round(rmse, 3)

0.088

In [43]:
#Lasso Regresssion and finding the Root Mean Square Error
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)

predicted_test = lasso_reg.predict(x_test)

rmse = np.sqrt(mean_squared_error(y_test, predicted_test))
round(rmse, 3)

0.094

In [44]:
#comparing the effects of regularisation
def get_weights_df(model, feat, col_name):
  #this function returns the weight of every feature
  weights = pd.Series(model.coef_, feat.columns).sort_values()
  weights_df = pd.DataFrame(weights).reset_index()
  weights_df.columns = ['Features', col_name]
  weights_df[col_name].round(3)
  return weights_df

In [47]:
linear_model_weights = get_weights_df(linear_model, x_train, 'linear_model_Weight')
ridge_weights_df = get_weights_df(ridge_reg, x_train, 'Ridge_Weight')
lasso_weights_df = get_weights_df(lasso_reg, x_train, 'Lasso_weight')

final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')

final_weights

       Features  linear_model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456698     -0.411071     -0.000000
1         T_out            -0.321860     -0.262172      0.000000
2            T2            -0.236178     -0.201397      0.000000
3            T9            -0.189941     -0.188916     -0.000000
4          RH_8            -0.157595     -0.156830     -0.000110
5        RH_out            -0.077671     -0.054724     -0.049557
6          RH_7            -0.044614     -0.045977     -0.000000
7          RH_9            -0.039800     -0.041367     -0.000000
8            T5            -0.015657     -0.019853     -0.000000
9            T1            -0.003281     -0.018406      0.000000
10          rv1             0.000770      0.000748     -0.000000
11          rv2             0.000770      0.000748     -0.000000
12  Press_mm_hg             0.006839      0.006584     -0.000000
13           T7             0.010319      0.010098     -0.000000
14   Visibility             0.012307      0.012076      0.000000
15         RH_5             0.016006      0.016152      0.000000
16         RH_4             0.026386      0.024579      0.000000
17           T4             0.028981      0.027384     -0.000000
18    Windspeed             0.029183      0.030268      0.002912
19         RH_6             0.038049      0.035519     -0.000000
20         RH_3             0.096048      0.095135      0.000000
21           T8             0.101995      0.101028      0.000000
22    Tdewpoint             0.117758      0.083128      0.000000
23           T6             0.236425      0.217292      0.000000
24           T3             0.290627      0.288087      0.000000
25         RH_1             0.553547      0.519525      0.017880